### ISSUE TITLE
Depotlocker container crash

### ISSUE THREAD

**Issue by Znote** [nekiro/TFS-1.4-Downgrades#9]
**Protocol version**
7.72/8.60

**Describe the bug**
Segmentation fault occurs after you have a looksie in your depotlocker. 

**To Reproduce**
1. Go to your depot
2. Open it
4. Logout
5. Login
5. Crash 

If it doesnt crash, do it a couple more times. It usually happens within the first 3 times I try it. 

**Expected behavior**
Nothing, no crash. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1552144/117570596-0abde980-b0cb-11eb-96e3-4d664aa21f75.png)

**Additional context**
```gdb
>> Loading monsters
>> Loading lua monsters
>> Loading outfits
>> Checking world type... PVP
>> Loading map
> Map size: 1024x1024.
> Map loading time: 4.164 seconds.
> Loaded house items in: 0.003 s
>> Initializing gamestate
>> Loaded all modules, server starting up...
>> server Server Online!

GM Znote has logged in.
GM Znote has logged out.
Luxitur has logged in.
Luxitur has logged out.
GM Znote has logged in.
GM Znote has logged out.
Luxitur has logged in.
GM Znote has logged in.
GM Znote has logged out.
Znote has logged in.
Znote has logged out.

Thread 2 "tfs" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5f80700 (LWP 16050)]
0x0000000000000000 in ?? ()
(gdb)


#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00005555555e6ae2 in Container::~Container (this=<optimized out>, __vtt_parm=<optimized out>, this=<optimized out>, __vtt_parm=<optimized out>) at /home/ubuntu/server/github/src/container.cpp:36
        item = 0x7ffff2ecca70
        __for_range = std::deque with 1 element = {0x7ffff2ecca70}
        __for_begin = 0x7ffff2ecca70
        __for_end = 0x0
        item = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#2  0x000055555560db67 in DepotLocker::~DepotLocker (this=<optimized out>, this=<optimized out>) at /home/ubuntu/server/github/src/depotlocker.h:27
No locals.
#3  0x000055555560db9c in DepotLocker::~DepotLocker (this=<optimized out>, this=<optimized out>) at /home/ubuntu/server/github/src/depotlocker.h:27
No locals.
#4  0x00005555558067c7 in std::_Sp_counted_ptr<DepotLocker*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7ffff3c51b70) at /usr/include/c++/9/bits/shared_ptr_base.h:377
No locals.
#5  0x0000555555598868 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7ffff3c51b70) at /usr/include/c++/9/bits/shared_ptr_base.h:155
No locals.
#6  0x00005555555983b9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
No locals.
#7  0x0000555555804996 in std::__shared_ptr<DepotLocker, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
No locals.
#8  0x00005555558049b0 in std::shared_ptr<DepotLocker>::~shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
No locals.
#9  0x00005555558049ce in std::pair<unsigned int const, std::shared_ptr<DepotLocker> >::~pair (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
No locals.
#10 0x00005555558049ec in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::destroy<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > (this=0x7ffff3c56590, __p=0x555555a71720) at /usr/include/c++/9/ext/new_allocator.h:153
No locals.
#11 0x00005555558035bf in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > > >::destroy<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > (__a=..., __p=0x555555a71720) at /usr/include/c++/9/bits/alloc_traits.h:497
No locals.
#12 0x0000555555801641 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_destroy_node (this=0x7ffff3c56590, __p=0x555555a71700) at /usr/include/c++/9/bits/stl_tree.h:642
No locals.
#13 0x00005555557fe6b1 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_drop_node (
    this=0x7ffff3c56590, __p=0x555555a71700) at /usr/include/c++/9/bits/stl_tree.h:650
No locals.
#14 0x00005555557fbafa in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_erase (
    this=0x7ffff3c56590, __x=0x555555a71700) at /usr/include/c++/9/bits/stl_tree.h:1915
        __y = 0x0
#15 0x00005555557f9b42 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::~_Rb_tree (
    this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_tree.h:995
No locals.
#16 0x00005555557e7a94 in std::map<unsigned int, std::shared_ptr<DepotLocker>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::~map (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_map.h:300
No locals.
#17 0x00005555557e909d in Player::~Player (this=<optimized out>, this=<optimized out>) at /home/ubuntu/server/github/src/player.cpp:54
        item = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#18 0x00005555557e9140 in Player::~Player (this=<optimized out>, this=<optimized out>) at /home/ubuntu/server/github/src/player.cpp:65
No locals.
#19 0x00005555555ef270 in Creature::decrementReferenceCounter (this=0x7ffff3c561b0) at /home/ubuntu/server/github/src/creature.h:462
No locals.
#20 0x000055555562f475 in Game::cleanup (this=0x555555a2c660 <g_game>) at /home/ubuntu/server/github/src/game.cpp:4323
        creature = 0x7ffff3c561b0
        __for_range = std::vector of length 1, capacity 16 = {0x7ffff3c561b0}
        __for_begin = 0x7ffff3c561b0
        __for_end = 0x7ffff3c52b70
#21 0x000055555562a508 in Game::checkCreatures (this=0x555555a2c660 <g_game>, index=2) at /home/ubuntu/server/github/src/game.cpp:3475
        checkCreatureList = std::__cxx11::list = {[0] = 0x7ffff3aa42a0}
        it = 0x1
        end = 0x1
#22 0x00005555556515eb in std::__invoke_impl<void, void (Game::*&)(unsigned long), Game*&, unsigned long&> (__f=@0x7fffe2953920: (void (Game::*)(Game * const, unsigned long)) 0x55555562a2ce <Game::checkCreatures(unsigned long)>, __t=@0x7fffe2953938: 0x555555a2c660 <g_game>) at /usr/include/c++/9/bits/invoke.h:73
No locals.
#23 0x000055555564d723 in std::__invoke<void (Game::*&)(unsigned long), Game*&, unsigned long&> (__fn=@0x7fffe2953920: (void (Game::*)(Game * const, unsigned long)) 0x55555562a2ce <Game::checkCreatures(unsigned long)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#24 0x00005555556483c8 in std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7fffe2953920, __args=...) at /usr/include/c++/9/functional:400
No locals.
#25 0x000055555564131f in std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)>::operator()<, void>() (this=0x7fffe2953920) at /usr/include/c++/9/functional:484
No locals.
#26 0x000055555563b053 in std::_Function_handler<void (), std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
No locals.
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x00005555558757d4 in std::function<void ()>::operator()() const (this=0x555555a733a0) at /usr/include/c++/9/bits/std_function.h:688
No locals.
#28 0x0000555555875246 in Task::operator() (this=0x555555a73390) at /home/ubuntu/server/github/src/tasks.h:41
No locals.
#29 0x00005555558754b2 in Dispatcher::threadMain (this=0x555555a2c540 <g_dispatcher>) at /home/ubuntu/server/github/src/tasks.cpp:57
        task = 0x555555a73390
        __for_range = std::vector of length 1, capacity 16 = {0x555555a73390}
        __for_begin = 0x555555a73390
        __for_end = 0x555555a63f80
        tmpTaskList = std::vector of length 1, capacity 16 = {0x555555a73390}
        taskLockUnique = {_M_device = 0x555555a2c550 <g_dispatcher+16>, _M_owns = false}
#30 0x00005555557db042 in std::__invoke_impl<void, void (Dispatcher::*)(), Dispatcher*> (__f=@0x555555a5b930: (void (Dispatcher::*)(Dispatcher * const)) 0x555555875370 <Dispatcher::threadMain()>, __t=@0x555555a5b928: 0x555555a2c540 <g_dispatcher>) at /usr/include/c++/9/bits/invoke.h:73
No locals.
#31 0x00005555557dad85 in std::__invoke<void (Dispatcher::*)(), Dispatcher*> (__fn=@0x555555a5b930: (void (Dispatcher::*)(Dispatcher * const)) 0x555555875370 <Dispatcher::threadMain()>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#32 0x00005555557da915 in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::_M_invoke<0ul, 1ul> (this=0x555555a5b928) at /usr/include/c++/9/thread:244
No locals.
#33 0x00005555557da32e in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::operator() (this=0x555555a5b928) at /usr/include/c++/9/thread:251
No locals.
#34 0x00005555557d9a7a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> > >::_M_run (this=0x555555a5b920) at /usr/include/c++/9/thread:195
No locals.
#35 0x00007ffff7e93d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#36 0x00007ffff7fa7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737320060672, 7447444098187041058, 140737488347358, 140737488347359, 140737488347360, 140737320058752, -7447466019741460190, -7447461720112064222}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#37 0x00007ffff7cd2293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb)
```

**Comment by EPuncker** [comment]
yeah it hasn't been "downgraded" yet ;P

**Comment by nekiro** [comment]
Can't seem to reproduce

**Comment by Znote** [comment]
Hmm interesting. I'm using Ubuntu 20.04. I will look a bit further into it.
Perhaps something with depot connected to id 0? Or a depotlocker without a town? :/

**Comment by nekiro** [comment]
I used default map that we have in this repo to check this.

**Comment by Znote** [comment]
Just tested latest commit. Was able to compile, runned 100% unmodified sources and datapack, getting same issue.
So looks to be Linux related.

**Comment by nekiro** [comment]
What about clean tfs, it does not crash?

**Comment by Znote** [comment]
OMG why didnt I think about that?! I can be so narrowminded sometimes...

Yes. This is an upstream bug, same thing happens in otland/forgottenserver. I will submit an issue there, and I will isolate the culprit by going back in time commit by commit to figure out which PR fucked it up.

**Comment by Znote** [comment]
Upstream tracker: https://github.com/otland/forgottenserver/issues/3450
